image: node:latest

pages:
  script:
    - npm config set registry https://registry.npm.taobao.org
    - npm install -g gitbook
    - test -e package.json && npm install
    - gitbook build
  artifacts:
    paths:
      - _book
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
