image: node:latest

pages:
  before_script:
    - mkdir ~/.ssh
    - echo $SSH_PRIVATE_KEY_DEV >> ~/.ssh/id_rsa
    - npm install -g gitbook-cli
    - test -e package.json && npm install
  script:
    - gitbook build
    - scp -P 26 -r _book/* $DEPLOY_USER@$DEPLOY_SERVER_DEV:$WEB_DIR 
  artifacts:
    paths:
      - _book
  cache:
    paths:
      - node_modules
    key: project
  only:
    - master
